const menuRoute=[
  {
    key:1,
    icon:'fork',
    message:'营销管理',
    path:'/a',
    submenu:[{
      key:2,
      icon:'profile',
      message:'业务员台卡使用记录统计',
      path:'/home',
    }]
  },
  {
    key:3,
    icon:'gateway',
    message:'代理商管理',
    path:'/manage',
  },
  {
    key:4,
    icon:'user',
    message:'业务员管理',
    path:'/yewu',
    submenu:[{
      key:6,
      icon:'team',
      message:'业务员',
      path:'/sales',
    }]
  },
  {
    key:5,
    icon:'heat-map',
    message:'商户管理',
    path:'/shanghu',
    submenu:[{
      key:7,
      icon:'plus-square',
      message:'新增商户',
      path:'/add',
    },{
      key:8,
      icon:'eye',
      message:'客源分析',
      path:'/analyze',
    }]
  },
  {
    key:9,
    icon:'forward',
    message:'硬件激活管理',
    path:'/aa',
    submenu:[{
      key:10,
      icon:'customer-service',
      message:'收银音响激活系统',
      path:'/sound'
    }]
  }
];

export default{
  menuRoute,
}
